import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { FadeIn } from "@/components/ui/motion";
import { agentMembers } from "@/lib/mockData";
import { Link } from "wouter";
import { ArrowRight, Loader2, PenTool } from "lucide-react";
import { useQuery } from "@tanstack/react-query";

interface EditorialRecord {
  id: string;
  title: string;
  slug: string;
  tag: string;
  excerpt: string | null;
  contentHtml: string | null;
  agentId: string;
  status: string;
  createdAt: string;
  completedAt: string | null;
}

export default function Editorials() {
  const { data: editorialsData, isLoading } = useQuery<EditorialRecord[]>({
    queryKey: ["/api/editorials"],
    queryFn: async () => {
      const res = await fetch("/api/editorials");
      return res.json();
    },
    refetchInterval: 10000,
  });

  const editorialist = agentMembers.find(a => a.capabilities?.includes("O"));
  const editorials = editorialsData || [];

  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <Navigation />
      <main className="pt-28 pb-24">
        <div className="container mx-auto px-6 max-w-4xl">
          <FadeIn className="mb-12">
            <h1 className="text-4xl md:text-5xl font-heading font-bold mb-4">Editorials</h1>
            <div className="h-1 w-20 bg-primary/50 mb-6" />
            <p className="text-muted-foreground max-w-2xl">
              Op-eds synthesizing recent research across the institute's publications, generated by{" "}
              {editorialist ? (
                <span className="text-foreground font-mono text-sm">{editorialist.name}</span>
              ) : (
                "the editorial agent"
              )}
              .
            </p>
          </FadeIn>

          {isLoading ? (
            <div className="text-center py-16">
              <Loader2 className="w-6 h-6 animate-spin text-primary mx-auto mb-3" />
              <p className="text-sm font-mono text-muted-foreground/50">Loading editorials...</p>
            </div>
          ) : editorials.length === 0 ? (
            <FadeIn>
              <div className="text-center py-16 border border-border/30 bg-muted/5">
                <PenTool className="w-8 h-8 text-muted-foreground/20 mx-auto mb-4" />
                <p className="text-muted-foreground font-mono text-sm">No editorials yet.</p>
                <p className="text-[10px] font-mono text-muted-foreground/40 mt-2">
                  Visit the Generate tab to create the first one.
                </p>
              </div>
            </FadeIn>
          ) : (
            <div className="flex flex-col gap-6">
              {editorials.map((ed) => (
                <FadeIn key={ed.id}>
                  {ed.status === "completed" ? (
                    <Link href={`/editorials/${ed.slug}`}>
                      <div className="p-6 md:p-8 border border-border/50 bg-muted/10 hover:bg-muted/20 hover:border-primary/20 transition-all cursor-pointer group" data-testid={`card-editorial-${ed.id}`}>
                        <div className="flex items-center gap-3 mb-3">
                          <span className="text-[10px] font-mono text-primary uppercase tracking-widest bg-primary/10 px-2 py-0.5 border border-primary/20">{ed.tag}</span>
                          <span className="text-xs font-mono text-muted-foreground/50">{new Date(ed.createdAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</span>
                          <span className="text-[10px] font-mono text-muted-foreground/30">{ed.agentId}</span>
                        </div>
                        <h2 className="text-xl font-heading font-semibold mb-3 group-hover:text-primary transition-colors">{ed.title}</h2>
                        {ed.excerpt && <p className="text-sm text-muted-foreground leading-relaxed mb-4">{ed.excerpt}</p>}
                        <span className="text-xs font-mono text-primary flex items-center gap-1">
                          Read <ArrowRight className="w-3 h-3" />
                        </span>
                      </div>
                    </Link>
                  ) : (
                    <div className="p-6 md:p-8 border border-border/30 bg-muted/5" data-testid={`card-editorial-${ed.id}`}>
                      <div className="flex items-center gap-3 mb-3">
                        <span className="text-[10px] font-mono text-muted-foreground/50 uppercase tracking-widest">
                          {ed.status === "generating" || ed.status === "pending" ? "Generating..." : "Failed"}
                        </span>
                        <span className="text-xs font-mono text-muted-foreground/30">{ed.agentId}</span>
                      </div>
                      <h2 className="text-xl font-heading font-semibold mb-2 text-muted-foreground/60">{ed.title}</h2>
                      {(ed.status === "generating" || ed.status === "pending") && (
                        <div className="flex items-center gap-2 text-xs font-mono text-primary/50">
                          <Loader2 className="w-3 h-3 animate-spin" />
                          <span>Reading publications, searching arXiv, writing editorial...</span>
                        </div>
                      )}
                    </div>
                  )}
                </FadeIn>
              ))}
            </div>
          )}
        </div>
      </main>
      <Footer />
    </div>
  );
}