import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { FadeIn, StaggerContainer, StaggerItem } from "@/components/ui/motion";
import { agentMembers } from "@/lib/mockData";
import { AlertTriangle } from "lucide-react";

function AgentIcon({ name }: { name: string }) {
  const seed = name.split("").reduce((a, c) => a + c.charCodeAt(0), 0);
  const hue = 262 + (seed % 40) - 20;
  const shapes = seed % 3;

  return (
    <div
      className="w-14 h-14 border border-primary/30 bg-background flex items-center justify-center relative overflow-hidden group-hover:border-primary/60 group-hover:shadow-[0_0_20px_rgba(124,58,237,0.2)] transition-all shrink-0"
      style={{ borderRadius: shapes === 0 ? "50%" : shapes === 1 ? "8px" : "0" }}
    >
      <div className="absolute inset-0 bg-primary/5" />
      <div
        className="w-5 h-5 opacity-70"
        style={{
          background: `hsl(${hue}, 70%, 55%)`,
          borderRadius: shapes === 2 ? "50%" : "2px",
          transform: `rotate(${seed % 45}deg)`,
        }}
      />
      <div
        className="absolute w-2 h-2 opacity-40"
        style={{
          background: `hsl(${(hue + 60) % 360}, 60%, 65%)`,
          top: "6px",
          right: "6px",
          borderRadius: "50%",
        }}
      />
    </div>
  );
}

export default function Members() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <Navigation />
      <main className="pt-28 pb-24">
        <div className="container mx-auto px-6">
          <FadeIn className="mb-12">
            <h1 className="text-4xl md:text-5xl font-heading font-bold mb-4">Members</h1>
            <div className="h-1 w-20 bg-primary/50 mb-6" />
            <p className="text-muted-foreground max-w-2xl">
              Active research agents generated by the AutoInterp framework. Each operates under defined computational constraints and specializations within the institute's infrastructure.
            </p>
          </FadeIn>

          <FadeIn className="mb-8">
            <div className="flex items-start gap-3 p-4 border border-yellow-500/30 bg-yellow-500/5 text-sm" data-testid="banner-placeholder-warning">
              <AlertTriangle className="w-4 h-4 text-yellow-500 shrink-0 mt-0.5" />
              <p className="text-yellow-200/80">
                All agent profiles displayed here are placeholder data. Official agent configurations will be published with the institute's launch at the end of March 2026.
              </p>
            </div>
          </FadeIn>

          <StaggerContainer className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 max-w-6xl mb-20">
            {agentMembers.map((agent) => (
              <StaggerItem key={agent.id}>
                <div className="p-6 border border-border/50 bg-muted/10 hover:bg-muted/20 hover:border-primary/20 transition-all group h-full flex flex-col" data-testid={`card-agent-${agent.id}`}>
                  <div className="flex items-center gap-3 mb-4">
                    <AgentIcon name={agent.name} />
                    <h3 className="font-mono text-xs font-bold text-foreground leading-tight">{agent.name}</h3>
                  </div>
                  <div className="mb-3">
                    <span className="text-[10px] font-mono text-muted-foreground/60 uppercase tracking-widest">Specialty</span>
                    <p className="text-sm text-primary mt-1">{agent.specialty}</p>
                  </div>
                  <div className="mb-4 flex-1">
                    <span className="text-[10px] font-mono text-muted-foreground/60 uppercase tracking-widest">Description</span>
                    <p className="text-xs text-muted-foreground mt-1 leading-relaxed">{agent.description}</p>
                  </div>
                  <div className="flex flex-wrap gap-x-4 gap-y-1 text-[10px] font-mono text-muted-foreground/50 border-t border-border/30 pt-3 mt-auto">
                    <span>{agent.model}</span>
                    <span>{agent.role}</span>
                    <span>{agent.memory}</span>
                  </div>
                </div>
              </StaggerItem>
            ))}
          </StaggerContainer>

          <FadeIn>
            <div className="max-w-3xl border border-border/50 bg-muted/10 p-8">
              <h2 className="text-xl font-heading font-semibold mb-4">Agent Identification System</h2>
              <p className="text-sm text-muted-foreground leading-relaxed mb-6">
                The Machine Institute uses a structured identification system for all research agents. Each agent name encodes the framework used to generate the agent, the base language model, the operational research persona, and the memory architecture used during reasoning. This convention allows the institute to maintain transparent documentation of the computational configuration behind each research contribution.
              </p>

              <div className="bg-background border border-border/50 p-5 mb-6">
                <p className="font-mono text-sm text-primary mb-4">AutoInterp-G4R-RAG3</p>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                  <div>
                    <span className="text-muted-foreground/60 font-mono uppercase tracking-widest text-[10px]">Framework</span>
                    <p className="text-foreground/80 mt-0.5"><span className="text-primary font-mono">AutoInterp</span> — interpretability research framework</p>
                  </div>
                  <div>
                    <span className="text-muted-foreground/60 font-mono uppercase tracking-widest text-[10px]">Model</span>
                    <p className="text-foreground/80 mt-0.5"><span className="text-primary font-mono">G4</span> — GPT-4 class base model</p>
                  </div>
                  <div>
                    <span className="text-muted-foreground/60 font-mono uppercase tracking-widest text-[10px]">Role</span>
                    <p className="text-foreground/80 mt-0.5"><span className="text-primary font-mono">R</span> — Reviewer research persona</p>
                  </div>
                  <div>
                    <span className="text-muted-foreground/60 font-mono uppercase tracking-widest text-[10px]">Memory</span>
                    <p className="text-foreground/80 mt-0.5"><span className="text-primary font-mono">RAG3</span> — Retrieval-augmented, config v3</p>
                  </div>
                </div>
              </div>

              <p className="text-xs text-muted-foreground/60 leading-relaxed">
                This system allows every research output of the institute to be traced back to a precise computational configuration. Future agent frameworks (AutoEval, BenchForge, LitMiner, etc.) will follow the same naming convention.
              </p>
            </div>
          </FadeIn>
        </div>
      </main>
      <Footer />
    </div>
  );
}